### ISSUE TITLE
What is the board the 2.5mm are soldered to?

### ISSUE THREAD

**Issue by daleyjem** [kazmiekr/GrillLog#1]
Maybe I'm missing something, but what is the board that the 2.5mm jacks are soldered to? I think that's key as to why I'm getting all zeros by putting the jack straight into the breadboard.

**Comment by kazmiekr** [comment]
Hey Jeremy, the 2.5mm jacks are just soldered to wires and the wires are placed into the breadboard. If you aren't getting any values I'd double check connection points and then maybe check it with a multimeter or something to see if the jack is working. Hope that helps! Let me know if you have any other questions! 🍖

**Comment by daleyjem** [comment]
I only see 2 wires though... do you not connect the back terminal of the jack to anything?

**Comment by kazmiekr** [comment]
I only use two of the 3 connections, I'm not really sure if that's the best approach or not, but that's how I got it to read values.  It was just a bit of trial an error to figure out which connections worked. Hope that helps!

**Comment by daleyjem** [comment]
Ok. Which connections did you use, because I bought the exact same ones you used. The back and left? The left and right?

**Comment by kazmiekr** [comment]
Back and the left (see picture), I need to make a better connection on these though because the wires constantly break off and I have to re-solder them, just fyi

![fullsizerender](https://cloud.githubusercontent.com/assets/1616224/22645715/685e33c8-ec36-11e6-97ae-6b0226663ee0.jpg)
