### ISSUE TITLE
Readings off

### ISSUE THREAD

**Issue by clomas** [kazmiekr/GrillLog#2]
Hello, 

I'm not sure if this is the best way to get in touch but I've attempted to use the source code. I'm using an ET-733 probe and a 1M ohm resistor but my readings are off by a bit. In boiling water my probe reads 184F and in water full of ice cubes it reads 44F. Is there anything I could be doing incorrectly? I'm new to programming for electronics, so apologies if it's something obvious. 

Thanks 
Clint

**Comment by kazmiekr** [comment]
Hey Clint! The calculations I used to convert the resistance to temperature aren't an exact thing unfortunately, I had to mess with the numbers a bit for my specific setup. You can read a bit about what I did on my medium post at https://medium.com/@kazmiekr/smoking-meat-with-the-internet-of-things-b047ecda94a0 or you can just try to mess with the beta coefficients in https://github.com/kazmiekr/GrillLog/blob/master/Arduino/GrillLog/GrillLog.ino#L34 . Not sure if that'll help you or not, but maybe it'll get you in the right direction. My temperatures were never really exact, they fluctuated a bit, but were close enough for me. Anytime the meat got close, I'd double check it with a different meat therm.

**Comment by clomas** [comment]
Thanks, I'll give it a go. There a a lot of code examples for the ET73 thermometers online, a lot of people recommend them over the thermometers we're using. Might end up trying them. Thanks again mate.

**Comment by kazmiekr** [comment]
Clint, let me know what you end up doing, I'd love to hear how people are actually using this code for things. 🍖 🔥
